#docker-compose.yml
services:
  jobs_retta:
    build:
      context: ./backend
    container_name: jobs_RETTA
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/var/www
    command: tail -f /dev/null 
    ports:
      - "8000:8000" 
    depends_on:
      - db_retta
    networks:
      - app-network

  react_retta:
    build:
      context: ./frontend
    container_name: react_RETTA
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - app-network

  db_retta:
    image: mysql:8.0
    container_name: db_RETTA
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deputados
      MYSQL_USER: deputado
      MYSQL_PASSWORD: retta
    ports:
      - "3310:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db_retta
      PMA_PORT: 3306
      PMA_USER: deputado
      PMA_PASSWORD: retta
    depends_on:
      - db_retta
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
